### ISSUE TITLE
[BUG] ANTHROPIC RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#108]
[errors.txt](https://github.com/kyegomez/swarms/files/13300667/errors.txt)
``

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/108">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/108/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/108/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
Missing api key.

This can be closed.
