### ISSUE TITLE
[BUG] Mistral modal killed 

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#110]
v@v-System-Product-Name:~/inhouse$ /bin/python3 /home/v/inhouse/mistral.py
Killed

Mistral example 
#######################################################################

from swarms.models import Mistral

model = Mistral()

task = "Summarize the main findings of the recen climate change report."

resutl = model.run(task)
print(resutl)

**Comment by kyegomez** [comment]
@vyomakesh09 It's your gpu memory, it's too low
