### ISSUE TITLE
Swarms Run Environment description

It would be nice if swarms reported a few details about the run environment:

OS
Versions
Whether access tokens are set. 
Configuration


### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#113]
**Is your feature request related to a problem? Please describe.**

To make debugging a little easier.

**Describe the solution you'd like**

Not too much data gathered, but enough to orient a little bit.

**Describe alternatives you've considered**

Live telemetry is a possibility, but can be very expensive.

Logging levels can be helpful, but also very expensive, and potentially a security issue.

**Additional context**
Trying to debug a selenium web driver issue, and had no idea if the system had chrome installed or not. Or if the python version was compatible with selenium.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/113">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/113/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/113/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell can you be more specific?

**Comment by evelynmitchell** [comment]
Yes. I'll write something up.
