### ISSUE TITLE
[BUG] ImportError: cannot import name 'SpeechToText' from 'swarms.models.whisperx'

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#122]
Traceback (most recent call last):
  File "/home/v/swarms/tests/models/whisperx.py", line 7, in <module>
    import whisperx
  File "/home/v/swarms/tests/models/whisperx.py", line 12, in <module>
    from swarms.models.whisperx import SpeechToText
ImportError: cannot import name 'SpeechToText' from 'swarms.models.whisperx' (/home/v/.local/lib/python3.10/site-packages/swarms/models/whisperx.py)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/122">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/122/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/122/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 Just fixed this by changing all SpeechToText -> WhisperX
