### ISSUE TITLE
[FIX][`OpenAIChat`]

### ISSUE THREAD

**Issue by kyegomez** [kyegomez/swarms#125]
## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/125">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/125/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/125/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
OpenAI API has changed significantly, we need to update it

**Comment by ZackBradshaw** [comment]
I'll start the refactoring

**Comment by ZackBradshaw** [comment]
finished refactor now getting 
`ERROR:root:Error generating response: Got unknown type`

**Comment by elder-plinius** [comment]
it should be chat.completions.create( )

**Comment by ZackBradshaw** [comment]
@kyegomez This is working and ready to merge

**Comment by evelynmitchell** [comment]
Never merged. Can we close this?
