### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'swarms.memory.vector_stores' 

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#137]
Traceback (most recent call last):
  File "/home/v/swarms/tests/memory/oceandb.py", line 3, in <module>
    from swarms.memory.ocean import OceanDB
  File "/home/v/.local/lib/python3.10/site-packages/swarms/memory/__init__.py", line 1, in <module>
    from swarms.memory.pinecone import PineconeVector
  File "/home/v/.local/lib/python3.10/site-packages/swarms/memory/pinecone.py", line 2, in <module>
    from swarms.memory.vector_stores.base import BaseVector
ModuleNotFoundError: No module named 'swarms.memory.vector_stores'

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/137">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/137/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/137/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 this has been fixed
