### ISSUE TITLE
[BUG] NameError: name 'getenv' is not defined

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#138]
Traceback (most recent call last):
  File "/home/v/swarms/tests/models/ada.py", line 6, in <module>
    from swarms.models.simple_ada import (
  File "/home/v/.local/lib/python3.10/site-packages/swarms/models/simple_ada.py", line 3, in <module>
    client = OpenAI(api_key=getenv("OPENAI_API_KEY"))
NameError: name 'getenv' is not defined

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/138">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/138/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/138/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 this code has been deleted!
