### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'playground'

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#139]
Traceback (most recent call last):
  File "/home/v/swarms/tests/models/dalle3.py", line 9, in <module>
    from playground.models.dalle3 import Dalle3
ModuleNotFoundError: No module named 'playground'

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/139">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/139/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/139/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 this has been fixed, the wrong import error
