### ISSUE TITLE
[BUG] AttributeError: partially initialized module 'whisperx' has no attribute 'DiarizationPipeline' (most likely due to a circular import)

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#141]
Traceback (most recent call last):
  File "/home/v/swarms/tests/models/whisperx.py", line 7, in <module>
    import whisperx
  File "/home/v/swarms/tests/models/whisperx.py", line 51, in <module>
    @patch.object(whisperx.DiarizationPipeline, "__call__")
AttributeError: partially initialized module 'whisperx' has no attribute 'DiarizationPipeline' (most likely due to a circular import)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/141">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/141/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/141/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 pls try again and run this test and lmk if it works
