### ISSUE TITLE
[BUG] Nougat wrong number positional args

### ISSUE THREAD

**Issue by elder-plinius** [kyegomez/swarms#146]
Traceback (most recent call last):
  File "C:\Users\Guest1\Desktop\swarms\playground\demos\accountant_team\accountant_team.py", line 22, in <module>
    answer = pdf_analyzer(
             ^^^^^^^^^^^^^
TypeError: Nougat.__call__() takes 2 positional arguments but 3 were given

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/146">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/146/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/146/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@elder-plinius this error has been eliminated. thanks
