### ISSUE TITLE
[BUG] Flow class logic seems to be repeating itself in its outputs (repeating same exact text multiple times in one output)

### ISSUE THREAD

**Issue by elder-plinius** [kyegomez/swarms#147]
AI: To create a playable Super Mario clone in your browser, you will need to write the necessary HTML code. The provided code serves as a starting point and sets up the basic structure and styling of the game.

Let's break down the code and understand its components:

1. The `<!DOCTYPE html>` declaration specifies that this is an HTML5 document.
2. The `<html>` element is the root element of the HTML page.
3. The `<head>` element contains meta-information about the document, such as the title and external CSS or JavaScript files.
4. The `<title>` element sets the title of the page, which is displayed in the browser's title bar or tab.
5. The `<style>` element contains CSS code to define the appearance and layout of the game.
6. The `#game-container` selector styles the main container for the game. It sets the width, height, background color, position, and overflow properties.
7. The `.character` selector styles the character elements in the game. It sets the width, height, position, and bottom properties.
8. The `#mario` selector styles the Mario character specifically. It sets the background color to red.
9. The `#platform` selector styles the platform element in the game. It sets the background color, width, height, position, bottom, and left properties.
10. The `<body>` element represents the content of the HTML page.
11. The `<div id="game-container">` creates the main container for the game.
12. The `<div id="mario" class="character">` creates the player character element, which is styled using the `character` class and the `mario` id.
13. The `<div id="platform">` creates the platform element, which Mario can stand on.
14. The `<script>` element is used to embed or reference JavaScript code.
15. The JavaScript code for the game logic should be added inside the `<script>` tags. This is where you would implement the game mechanics, physics, and controls.

Keep in mind that the provided code is just a starting point, and you will need to invest significant time and effort to develop a complete game. Creating a fully functional Super Mario clone is a complex task that requires advanced programming knowledge and skills.
To create a playable Super Mario clone in your browser, you will need to write the necessary HTML code. The provided code serves as a starting point and sets up the basic structure and styling of the game.

Let's break down the code and understand its components:

1. The `<!DOCTYPE html>` declaration specifies that this is an HTML5 document.
2. The `<html>` element is the root element of the HTML page.
3. The `<head>` element contains meta-information about the document, such as the title and external CSS or JavaScript files.
4. The `<title>` element sets the title of the page, which is displayed in the browser's title bar or tab.
5. The `<style>` element contains CSS code to define the appearance and layout of the game.
6. The `#game-container` selector styles the main container for the game. It sets the width, height, background color, position, and overflow properties.
7. The `.character` selector styles the character elements in the game. It sets the width, height, position, and bottom properties.
8. The `#mario` selector styles the Mario character specifically. It sets the background color to red.
9. The `#platform` selector styles the platform element in the game. It sets the background color, width, height, position, bottom, and left properties.
10. The `<body>` element represents the content of the HTML page.
11. The `<div id="game-container">` creates the main container for the game.
12. The `<div id="mario" class="character">` creates the player character element, which is styled using the `character` class and the `mario` id.
13. The `<div id="platform">` creates the platform element, which Mario can stand on.
14. The `<script>` element is used to embed or reference JavaScript code.
15. The JavaScript code for the game logic should be added inside the `<script>` tags. This is where you would implement the game mechanics, physics, and controls.

Keep in mind that the provided code is just a starting point, and you will need to invest significant time and effort to develop a complete game. Creating a fully functional Super Mario clone is a complex task that requires advanced programming knowledge and skills.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/147">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/147/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/147/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@elder-plinius what should we do? How can we fix this?

**Comment by kyegomez** [comment]
@elder-plinius i have fixed this with a print statement
