### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by bryonmccoy** [kyegomez/swarms#148]
the import instruction in the omni...pd example is missing the omni.modal.agent after the .swarms.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/148">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/148/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/148/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@bryonmccoy just added more docs
