### ISSUE TITLE
[BUG] griptape no matching version

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#154]
The run_test.yml action is failing due to griptape dependency.
```
ERROR: Could not find a version that satisfies the requirement griptape (from versions: none)
ERROR: No matching distribution found for griptape
```
(https://github.com/kyegomez/swarms/actions/runs/6910013445)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/154">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/154/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/154/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell griptape has been officially removed from Swarms

**Comment by evelynmitchell** [comment]
Thanks. I'll sort out the requirements.

**Comment by evelynmitchell** [comment]
Basechunker.md mentions griptape
I don't know what basechunker is.

**Comment by evelynmitchell** [comment]
swarms/artifacts/base.py looks like it needs a section deleted:
```
 def from_dict(cls, artifact_dict: dict) -> BaseArtifact:
        from griptape.schemas import (
            TextArtifactSchema,
            InfoArtifactSchema,
            ErrorArtifactSchema,
            BlobArtifactSchema,
            CsvRowArtifactSchema,
            ListArtifactSchema,
        )

        class_registry.register("TextArtifact", TextArtifactSchema)
        class_registry.register("InfoArtifact", InfoArtifactSchema)
        class_registry.register("ErrorArtifact", ErrorArtifactSchema)
        class_registry.register("BlobArtifact", BlobArtifactSchema)
        class_registry.register("CsvRowArtifact", CsvRowArtifactSchema)
        class_registry.register("ListArtifact", ListArtifactSchema)

        try:
            return class_registry.get_class(artifact_dict["type"])().load(artifact_dict)
        except RegistryError:
            raise ValueError("Unsupported artifact type")
```

**Comment by evelynmitchell** [comment]
swarms/artifacts/error_artifact.py also needs a section removed:
```
    def to_dict(self) -> dict:
        from griptape.schemas import ErrorArtifactSchema

        return dict(ErrorArtifactSchema().dump(self))
```

**Comment by evelynmitchell** [comment]
swarms/artifacts/memory.py remove:
```
from griptape.artifacts import TextArtifact
``
and every other reference in memory.py to TextArtifact.

**Comment by evelynmitchell** [comment]
I'll commit the change to requirements and pyproject
