### ISSUE TITLE
[BUG] Accountant demo error

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#157]
**Describe the bug**
Using a colab notebook to run the accountant demo with the image pulled from this repo.

```
AttributeError                            Traceback (most recent call last)

[<ipython-input-1-ffa43f172f2b>](https://localhost:8080/#) in <cell line: 19>()
     17 
     18 # LayoutLM Document QA
---> 19 pdf_analyzer = LayoutLMDocumentQA()
     20 
     21 question = "What is the total amount of expenses?"

[/usr/local/lib/python3.10/dist-packages/swarms/models/layoutlm_document_qa.py](https://localhost:8080/#) in __init__(self, model_name, task_type)
     27         task_type: str = "document-question-answering",
     28     ):
---> 29         self.pipeline = pipeline(self.task_type, model=self.model_name)
     30 
     31     def __call__(self, task: str, img_path: str):

AttributeError: 'LayoutLMDocumentQA' object has no attribute 'task_type'
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/157">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/157/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/157/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
The docs for the library are: https://huggingface.co/impira/layoutlm-document-qa

**Comment by evelynmitchell** [comment]
The fix looks to me to be removing line 27 of swarms/models/layoutlm_document_qa.py

**Comment by kyegomez** [comment]
@evelynmitchell i have fixed the input parameter with this class

**Comment by evelynmitchell** [comment]
Thank you!
