### ISSUE TITLE
[BUG] torch.distributed

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#161]
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmp312csgvg
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmp312csgvg/_remote_module_non_scriptable.py

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/161">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/161/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/161/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 tried to fix now
