### ISSUE TITLE
[BUG] code cleanup account_team2.py - whitespace only

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#163]
./account_team2.py:48:9: E225 missing whitespace around operator from flake8 lint

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/163">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/163/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/163/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell try the `code_quality.sh` shell command
