### ISSUE TITLE
[BUG] remove unused test worker_agent_ultra.py

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#171]
ruff lint reported 
```
 tests/workers/worker_agent_ultra.py:45:14: F821 Undefined name `worker_ultra_node`
tests/workers/worker_agent_ultra.py:51:9: F821 Undefined name `worker_ultra_node`
```
It appears that this test is for a worker which doesn't exist:
swarms/tests/workers/worker_agent_ultra.py

My recommended fix is to delete swarms/tests/workers/worker_agent_ultra.py

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/171">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/171/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/171/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell this code has been deleted

**Comment by evelynmitchell** [comment]
Thanks Kye. You're the best.
