### ISSUE TITLE
Chain isn't working[BUG] 

### ISSUE THREAD

**Issue by bryonmccoy** [kyegomez/swarms#173]
**Describe the bug**
But is one agent not talking to another agent.

**To Reproduce**
Run the file and see if it asks you for information about the student and then passes that info to the next agent. 

**Expected behavior**
The above is the expected behavior

**Screenshots**

**Additional context**
This code pulls the prompts from actual prompt json files. I'll include the files for you and you'll need to put them in the root of swarms to use them. 
[base_code.txt](https://github.com/kyegomez/swarms/files/13443685/base_code.txt)
[personality_profile_test_prompts.json](https://github.com/kyegomez/swarms/files/13443688/personality_profile_test_prompts.json)
[reformatted_second_bot_instructions.json](https://github.com/kyegomez/swarms/files/13443689/reformatted_second_bot_instructions.json)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/173">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/173/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/173/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
Can this be closed?

**Comment by bryonmccoy** [comment]
Yes


Bryon McCoy
Practicing Musician
***@***.***
509-406-2419
practicingmusician.com
<http://practicingmusician.com/>
________________________________
