### ISSUE TITLE
[BUG] tests Dockerfile will not build

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#178]
**Describe the bug**
In swarms/tests, there is a Dockerfile which uses poetry to run the application.

```
docker build . -t swarmstests
```
fails with
```
=> ERROR [6/8] RUN poetry install --no-interaction --no-ansi              1.3s 
------                                                                          
 > [6/8] RUN poetry install --no-interaction --no-ansi:                         
1.235                                                                           
1.235 Poetry could not find a pyproject.toml file in /usr/src/app or its parents
------
Dockerfile:24
--------------------
  22 |     # Disable virtualenv creation by poetry and install dependencies
  23 |     RUN poetry config virtualenvs.create false
  24 | >>> RUN poetry install --no-interaction --no-ansi
  25 |     
  26 |     # Install the 'swarms' package if it's not included in the poetry.lock
--------------------
ERROR: failed to solve: process "/bin/sh -c poetry install --no-interaction --no-ansi" did not complete successfully: exit code: 1

```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/178">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/178/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/178/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell I have fixed this issue

**Comment by evelynmitchell** [comment]
Thanks!
