### ISSUE TITLE
[BUG] CONTRIBUTING.md refers to branching

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#179]
**Describe the bug**
CONTRIBUTING.md refers to branching.

**Expected behavior**
The policy of this team is to commit to main.
The doc needs to be updated for current policy.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/179">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/179/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/179/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell can you elaborate?

**Comment by evelynmitchell** [comment]
You mentioned yesterday that you want a push to main style of commit.
