### ISSUE TITLE
[BUG] sequential_workflow_example error (shouldn't be dependent on anthropic key to run)

### ISSUE THREAD

**Issue by elder-plinius** [kyegomez/swarms#182]
Traceback (most recent call last):
  File "C:\Users\Guest1\Desktop\pliny-swarms\sequential_workflow_example.py", line 19, in <module>
    anthropic = Anthropic()
                ^^^^^^^^^^^
  File "C:\Users\Guest1\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\load\serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Anthropic
__root__
  Did not find anthropic_api_key, please add an environment variable `ANTHROPIC_API_KEY` which contains it, or pass  `anthropic_api_key` as a named parameter. (type=value_error)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/182">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/182/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/182/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@elder-plinius this is a choice of which llm to use, you can comment it out if you do not use anthropic
