### ISSUE TITLE
[BUG] positive_med demo not running, looks like old import doesnt exist now

### ISSUE THREAD

**Issue by elder-plinius** [kyegomez/swarms#183]
Traceback (most recent call last):
  File "C:\Users\Guest1\Desktop\pliny-swarms\playground\demos\positive_med\positive_med.py", line 24, in <module>
    from swarms.prompts.autoblogen import (
ModuleNotFoundError: No module named 'swarms.prompts.autoblogen'

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/183">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/183/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/183/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@elder-plinius fixed the file import path
