### ISSUE TITLE
[BUG] positive med

### ISSUE THREAD

**Issue by elder-plinius** [kyegomez/swarms#185]
C:\Users\Guest1\Desktop\p-swarms\playground\demos\positive_med>python positive_med.py
  File "C:\Users\Guest1\Desktop\p-swarms\playground\demos\positive_med\positive_med.py", line 25
    from swarms.prompts.autobloggen
                                   ^
SyntaxError: invalid syntax

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/185">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/185/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/185/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@elder-plinius this has been fixed. i have fixed it
