### ISSUE TITLE
[BUG] In the basic example in Colab, flow.run() is missing a parameter

### ISSUE THREAD

**Issue by gultar** [kyegomez/swarms#192]
**Describe the bug**
I ran the colab for the basic example to test its capacities, and I got the following error.

TypeError                                 Traceback (most recent call last)
[<ipython-input-1-b6b873294935>](https://localhost:8080/#) in <cell line: 32>()
     30 # temp = flow.dynamic_temperature()
     31 # filter = flow.add_response_filter("Trump")
---> 32 out = flow.run(
     33     "Generate a 10,000 word blog on mental clarity and the benefits of meditation."
     34 )

TypeError: Flow.run() missing 1 required positional argument: 'img'

**Additional context**
The second argument in the run method seems to be optional, but I had to pass an empty string "" to make it work.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/192">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/192/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/192/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@gultar Thanks for letting me know, I have fixed this by making img = None!
