### ISSUE TITLE
[BUG] tests/models/test_distill_whisper.py:118: AssertionError

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#219]
/home/v/swarms/tests/models/test_distill_whisper.py::test_real_time_transcribe failed: distil_whisper_model = <swarms.models.distilled_whisperx.DistilWhisperModel object at 0x7f6a4d814cd0>
capsys = <_pytest.capture.CaptureFixture object at 0x7f6a4e11bf10>

    def test_real_time_transcribe(distil_whisper_model, capsys):
        test_data = np.random.rand(
            16000 * 5
        )  # Simulated audio data (5 seconds)
        with tempfile.NamedTemporaryFile(
            suffix=".wav", delete=False
        ) as audio_file:
            audio_file_path = create_audio_file(
                test_data, 16000, audio_file.name
            )
    
            distil_whisper_model.real_time_transcribe(
                audio_file_path, chunk_duration=1
            )
    
            os.remove(audio_file_path)
    
        captured = capsys.readouterr()
>       assert "Starting real-time transcription..." in captured.out
E       assert 'Starting real-time transcription...' in "An error occurred during transcription: 'WhisperProcessor' object has no attribute 'audio_file_to_array'\n"
E        +  where "An error occurred during transcription: 'WhisperProcessor' object has no attribute 'audio_file_to_array'\n" = CaptureResult(out="An error occurred during transcription: 'WhisperProcessor' object has no attribute 'audio_file_to_array'\n", err='').out

tests/models/test_distill_whisper.py:118: AssertionError

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/219">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/219/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/219/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
I've fixed this, it can be closed.

**Comment by evelynmitchell** [comment]
This can be closed.
