### ISSUE TITLE
[BUG]  AssertionError: assert 'Starting real-time transcription...' in 'The audio file was not found.\n' E   +  where 'The audio file was not found.\n' = CaptureResult(out='The audio file was not found.\n', err='').out

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#221]
/home/v/swarms/tests/models/test_distill_whisper.py::test_real_time_transcription failed: whisper_model = <swarms.models.distilled_whisperx.DistilWhisperModel object at 0x7f6a4e11bd00>
audio_file_path = 'path/to/valid_audio.mp3'
capsys = <_pytest.capture.CaptureFixture object at 0x7f6a4e1e4400>

    def test_real_time_transcription(
        whisper_model, audio_file_path, capsys
    ):
        whisper_model.real_time_transcribe(
            audio_file_path, chunk_duration=1
        )
        captured = capsys.readouterr()
>       assert "Starting real-time transcription..." in captured.out
E      ```
 AssertionError: assert 'Starting real-time transcription...' in 'The audio file was not found.\n'
E        +  where 'The audio file was not found.\n' = CaptureResult(out='The audio file was not found.\n', err='').out

```
tests/models/test_distill_whisper.py:290: AssertionError


<!-- POLAR PLEDGE BADGE START -->
## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/221">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/221/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/221/pledge.svg">
</picture>
</a>
<!-- POLAR PLEDGE BADGE END -->

**Comment by evelynmitchell** [comment]
This can be closed.
