### ISSUE TITLE
[BUG] KeyError: 'message'

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#222]
/home/v/swarms/tests/models/test_gpt4_vision_api.py::test_run_success failed: vision_api = <swarms.models.gpt4_vision_api.GPT4VisionAPI object at 0x7f6a4d8116f0>

    def test_run_success(vision_api):
        expected_response = {
            "choices": [{"text": "This is the model's response."}]
        }
        with patch(
            "requests.post",
            return_value=Mock(json=lambda: expected_response),
        ) as mock_post:
>           result = vision_api.run("What is this?", img)

tests/models/test_gpt4_vision_api.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
swarms/models/gpt4_vision_api.py:174: in run
    raise error
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <swarms.models.gpt4_vision_api.GPT4VisionAPI object at 0x7f6a4d8116f0>
task = 'What is this?', img = 'images/swarms.jpeg', args = (), kwargs = {}
base64_image = '/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoK...AA5+i/5Ldz/i+/0e/0T7/yhB6D/wD4AEVC6L/WhDNn6uzTMEItfn+7z/KifrXhf3/o2qE8h/dSFBfo/qTJk/y+b7/w/wB/+Z5/V5/d8/wU/tj39PMOZ//Z'
headers = {'Authorization': 'Bearer None', 'Content-Type': 'application/json'}
payload = {'max_tokens': 300, 'messages': [{'content': ['\nYou are an multi-modal autonomous agent. You are given a task and an ...fo/qTJk/y+b7/w/wB/+Z5/V5/d8/wU/tj39PMOZ//Z'}, 'type': 'image_url'}], 'role': 'user'}], 'model': 'gpt-4-vision-preview'}
response = <Mock id='140094552986848'>
out = {'choices': [{'text': "This is the model's response."}]}

    def run(
        self,
        task: Optional[str] = None,
        img: Optional[str] = None,
        *args,
        **kwargs,
    ):
        """Run the model."""
        try:
            base64_image = self.encode_image(img)
            headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {openai_api_key}",
            }
            payload = {
                "model": self.model_name,
                "messages": [
                    {
                        "role": "system",
                        "content": [self.system_prompt],
                    },
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": task},
                            {
                                "type": "image_url",
                                "image_url": {
                                    "url": f"data:image/jpeg;base64,{base64_image}"
                                },
                            },
                        ],
                    },
                ],
                "max_tokens": self.max_tokens,
            }
            response = requests.post(
                self.openai_proxy,
                headers=headers,
                json=payload,
            )
    
            out = response.json()
>           content = out["choices"][0]["message"]["content"]
E           KeyError: 'message'

swarms/models/gpt4_vision_api.py:159: KeyError

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/222">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/222/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/222/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 this error has been eliminated
