### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#224]
/home/v/swarms/tests/models/test_huggingface.py::test_llm_set_device[cpu] failed: llm_instance = <swarms.models.huggingface.HuggingfaceLLM object at 0x7f6a4e12fb20>
device = 'cpu'

    @pytest.mark.parametrize("device", ["cpu", "cuda"])
    def test_llm_set_device(llm_instance, device):
>       llm_instance.set_device(device)

tests/models/test_huggingface.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <swarms.models.huggingface.HuggingfaceLLM object at 0x7f6a4e12fb20>
device = 'cpu'

    def set_device(self, device):
        """
        Changes the device used for inference.
    
        Parameters
        ----------
            device : str
                The new device to use for inference.
        """
        self.device = device
>       self.model.to(self.device)
E       AttributeError: 'NoneType' object has no attribute 'to'

swarms/models/huggingface.py:454: AttributeError

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/224">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/224/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/224/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 I have fixed this by adding checks
