### ISSUE TITLE
[BUG] AttributeError: 'dict' object has no attribute 'to'

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#232]
/home/v/swarms/tests/models/test_idefics.py::test_run failed: idefics_instance = <swarms.models.idefics.Idefics object at 0x7f6a4c128a60>

    def test_run(idefics_instance):
        prompts = [["User: Test"]]
        with patch.object(
            idefics_instance, "processor"
        ) as mock_processor, patch.object(
            idefics_instance, "model"
        ) as mock_model:
            mock_processor.return_value = {
                "input_ids": torch.tensor([1, 2, 3])
            }
            mock_model.generate.return_value = torch.tensor([1, 2, 3])
            mock_processor.batch_decode.return_value = ["Test"]
    
>           result = idefics_instance.run(prompts)

tests/models/test_idefics.py:58: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <swarms.models.idefics.Idefics object at 0x7f6a4c128a60>
prompts = [['User: Test']], batched_mode = True

    def run(self, prompts, batched_mode=True):
        """
        Generates text based on the provided prompts.
    
        Parameters
        ----------
            prompts : list
                A list of prompts. Each prompt is a list of text strings and images.
            batched_mode : bool, optional
                Whether to process the prompts in batched mode. If True, all prompts are
                processed together. If False, only the first prompt is processed (default is True).
    
        Returns
        -------
            list
                A list of generated text strings.
        """
        inputs = (
            self.processor(
                prompts,
                add_end_of_utterance_token=False,
                return_tensors="pt",
>           ).to(self.device)
            if batched_mode
            else self.processor(prompts[0], return_tensors="pt").to(
                self.device
            )
        )
E       AttributeError: 'dict' object has no attribute 'to'

swarms/models/idefics.py:106: AttributeError

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/232">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/232/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/232/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 I have just optimized this method and made it much better
