### ISSUE TITLE
[BUG] no attribute "create"

### ISSUE THREAD

**Issue by elder-plinius** [kyegomez/swarms#265]
ERROR:root:Error generating response: 'NoneType' object has no attribute 'create'
Error generating response: 'NoneType' object has no attribute 'create'
ERROR:root:Error generating response: 'NoneType' object has no attribute 'create'
Error generating response: 'NoneType' object has no attribute 'create'
ERROR:root:Error generating response: 'NoneType' object has no attribute 'create'
Error generating response: 'NoneType' object has no attribute 'create'

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/265">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/265/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/265/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@elder-plinius provide the full error stack trace what file are you trying to run, this is useless
