### ISSUE TITLE
[BUG] AssertionError: Expected 'create_engine' to have been called once. Called 0 times.

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#271]
/home/v/swarms/tests/memory/test_pg.py::test_init failed: def test_init():
        with patch("sqlalchemy.create_engine") as MockEngine:
            store = PgVectorVectorStore(
                embedding_driver=mock_embedding_driver,
                connection_string=PSG_CONNECTION_STRING,
                table_name="test",
            )
>           MockEngine.assert_called_once()

tests/memory/test_pg.py:22: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <MagicMock name='create_engine' id='139931849939488'>

    def assert_called_once(self):
        """assert that the mock was called only once.
        """
        if not self.call_count == 1:
            msg = ("Expected '%s' to have been called once. Called %s times.%s"
                   % (self._mock_name or 'mock',
                      self.call_count,
                      self._calls_repr()))
>           raise AssertionError(msg)
E           AssertionError: Expected 'create_engine' to have been called once. Called 0 times.

/usr/lib/python3.10/unittest/mock.py:908: AssertionError

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/271">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/271/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/271/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
This can be closed.
