### ISSUE TITLE
[BUG] ../.local/lib/python3.10/site-packages/psycopg2/__init__.py:122: OperationalError

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#272]
/home/v/swarms/tests/memory/test_pg.py::test_setup failed: self = Engine(postgresql://mockuser:***@localhost:5432/mockdb)
fn = <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f446c084c10>>
connection = None

    def _wrap_pool_connect(self, fn, connection):
        dialect = self.dialect
        try:
>           return fn()

../.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3371: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:327: in connect
    return _ConnectionFairy._checkout(self)
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:894: in _checkout
    fairy = _ConnectionRecord.checkout(pool)
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:493: in checkout
    rec = pool._do_get()
../.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:145: in _do_get
    with util.safe_reraise():
../.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:70: in __exit__
    compat.raise_(
../.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py:211: in raise_
    raise exception
../.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:143: in _do_get
    return self._create_connection()
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:273: in _create_connection
    return _ConnectionRecord(self)
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:388: in __init__
    self.__connect()
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:690: in __connect
    with util.safe_reraise():
../.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:70: in __exit__
    compat.raise_(
../.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py:211: in raise_
    raise exception
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:686: in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
../.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py:574: in connect
    return dialect.connect(*cargs, **cparams)
../.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py:598: in connect
    return self.dbapi.connect(*cargs, **cparams)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

dsn = 'host=localhost user=mockuser password=mockpassword port=5432 dbname=mockdb'
connection_factory = None, cursor_factory = None
kwargs = {'database': 'mockdb', 'host': 'localhost', 'password': 'mockpassword', 'port': 5432, ...}
kwasync = {}

    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):
        """
        Create a new database connection.
    
        The connection parameters can be specified as a string:
    
            conn = psycopg2.connect("dbname=test user=postgres password=secret")
    
        or using a set of keyword arguments:
    
            conn = psycopg2.connect(database="test", user="postgres", password="secret")
    
        Or as a mix of both. The basic connection parameters are:
    
        - *dbname*: the database name
        - *database*: the database name (only as keyword argument)
        - *user*: user name used to authenticate
        - *password*: password used to authenticate
        - *host*: database host address (defaults to UNIX socket if not provided)
        - *port*: connection port number (defaults to 5432 if not provided)
    
        Using the *connection_factory* parameter a different class or connections
        factory can be specified. It should be a callable object taking a dsn
        argument.
    
        Using the *cursor_factory* parameter, a new default cursor factory will be
        used by cursor().
    
        Using *async*=True an asynchronous connection will be created. *async_* is
        a valid alias (for Python versions where ``async`` is a keyword).
    
        Any other keyword parameter will be passed to the underlying client
        library: the list of supported parameters depends on the library version.
    
        """
        kwasync = {}
        if 'async' in kwargs:
            kwasync['async'] = kwargs.pop('async')
        if 'async_' in kwargs:
            kwasync['async_'] = kwargs.pop('async_')
    
        dsn = _ext.make_dsn(dsn, **kwargs)
>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
E       psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
E       	Is the server running on that host and accepting TCP/IP connections?

../.local/lib/python3.10/site-packages/psycopg2/__init__.py:122: OperationalError

The above exception was the direct cause of the following exception:

    def test_setup():
        with patch("sqlalchemy.create_engine") as MockEngine:
            store = PgVectorVectorStore(
                embedding_driver=mock_embedding_driver,
                connection_string=PSG_CONNECTION_STRING,
                table_name="test",
            )
>           store.setup()

tests/memory/test_pg.py:42: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
swarms/memory/pg.py:163: in setup
    self.engine.execute(
<string>:2: in execute
    ???
../.local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py:468: in warned
    return fn(*args, **kwargs)
../.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3266: in execute
    connection = self.connect(close_with_result=True)
../.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3325: in connect
    return self._connection_cls(self, close_with_result=close_with_result)
../.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py:96: in __init__
    else engine.raw_connection()
../.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3404: in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
../.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3374: in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
../.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py:2208: in _handle_dbapi_exception_noconnection
    util.raise_(
../.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py:211: in raise_
    raise exception
../.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3371: in _wrap_pool_connect
    return fn()
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:327: in connect
    return _ConnectionFairy._checkout(self)
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:894: in _checkout
    fairy = _ConnectionRecord.checkout(pool)
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:493: in checkout
    rec = pool._do_get()
../.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:145: in _do_get
    with util.safe_reraise():
../.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:70: in __exit__
    compat.raise_(
../.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py:211: in raise_
    raise exception
../.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:143: in _do_get
    return self._create_connection()
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:273: in _create_connection
    return _ConnectionRecord(self)
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:388: in __init__
    self.__connect()
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:690: in __connect
    with util.safe_reraise():
../.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:70: in __exit__
    compat.raise_(
../.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py:211: in raise_
    raise exception
../.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py:686: in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
../.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py:574: in connect
    return dialect.connect(*cargs, **cparams)
../.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py:598: in connect
    return self.dbapi.connect(*cargs, **cparams)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

dsn = 'host=localhost user=mockuser password=mockpassword port=5432 dbname=mockdb'
connection_factory = None, cursor_factory = None
kwargs = {'database': 'mockdb', 'host': 'localhost', 'password': 'mockpassword', 'port': 5432, ...}
kwasync = {}

    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):
        """
        Create a new database connection.
    
        The connection parameters can be specified as a string:
    
            conn = psycopg2.connect("dbname=test user=postgres password=secret")
    
        or using a set of keyword arguments:
    
            conn = psycopg2.connect(database="test", user="postgres", password="secret")
    
        Or as a mix of both. The basic connection parameters are:
    
        - *dbname*: the database name
        - *database*: the database name (only as keyword argument)
        - *user*: user name used to authenticate
        - *password*: password used to authenticate
        - *host*: database host address (defaults to UNIX socket if not provided)
        - *port*: connection port number (defaults to 5432 if not provided)
    
        Using the *connection_factory* parameter a different class or connections
        factory can be specified. It should be a callable object taking a dsn
        argument.
    
        Using the *cursor_factory* parameter, a new default cursor factory will be
        used by cursor().
    
        Using *async*=True an asynchronous connection will be created. *async_* is
        a valid alias (for Python versions where ``async`` is a keyword).
    
        Any other keyword parameter will be passed to the underlying client
        library: the list of supported parameters depends on the library version.
    
        """
        kwasync = {}
        if 'async' in kwargs:
            kwasync['async'] = kwargs.pop('async')
        if 'async_' in kwargs:
            kwasync['async_'] = kwargs.pop('async_')
    
        dsn = _ext.make_dsn(dsn, **kwargs)
>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
E       sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
E       	Is the server running on that host and accepting TCP/IP connections?
E       
E       (Background on this error at: https://sqlalche.me/e/14/e3q8)

../.local/lib/python3.10/site-packages/psycopg2/__init__.py:122: OperationalError

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/272">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/272/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/272/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
This can be closed.
