### ISSUE TITLE
[BUG] assert None == "This is the model's response."

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#276]
/home/v/swarms/tests/models/test_gpt4_vision_api.py::test_run_success failed: vision_api = <swarms.models.gpt4_vision_api.GPT4VisionAPI object at 0x7fd96c9477f0>

    def test_run_success(vision_api):
        expected_response = {"This is the model's response."}
        with patch(
            "requests.post",
            return_value=Mock(json=lambda: expected_response),
        ) as mock_post:
            result = vision_api.run("What is this?", img)
            mock_post.assert_called_once()
>           assert result == "This is the model's response."
E           assert None == "This is the model's response."

tests/models/test_gpt4_vision_api.py:45: AssertionError

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/276">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/276/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/276/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
This can be closed.
