### ISSUE TITLE
[BUG]            Failed: DID NOT RAISE <class 'requests.exceptions.RequestException'>

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#277]
/home/v/swarms/tests/models/test_gpt4_vision_api.py::test_run_request_error failed: vision_api = <swarms.models.gpt4_vision_api.GPT4VisionAPI object at 0x7fd96db40c40>

    def test_run_request_error(vision_api):
        with patch(
            "requests.post", side_effect=RequestException("Request Error")
        ) as mock_post:
>           with pytest.raises(RequestException):
E           Failed: DID NOT RAISE <class 'requests.exceptions.RequestException'>

tests/models/test_gpt4_vision_api.py:52: Failed

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/277">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/277/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/277/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
This can be closed.
