### ISSUE TITLE
[BUG] AssertionError: assert None == 'Answer from GPT-4 Vision'

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#278]
/home/v/swarms/tests/models/test_gpt4_vision_api.py::test_run_successful_response failed: gpt_api = <swarms.models.gpt4_vision_api.GPT4VisionAPI object at 0x7fd96d388f40>

    def test_run_successful_response(gpt_api):
        task = "What is in the image?"
        img_url = img
        response_json = {
            "choices": [{"text": "Answer from GPT-4 Vision"}]
        }
        mock_response = Mock()
        mock_response.json.return_value = response_json
        with patch(
            "requests.post", return_value=mock_response
        ) as mock_post:
            result = gpt_api.run(task, img_url)
            mock_post.assert_called_once()
>       assert result == response_json["choices"][0]["text"]
E       AssertionError: assert None == 'Answer from GPT-4 Vision'

tests/models/test_gpt4_vision_api.py:108: AssertionError

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/278">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/278/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/278/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
This can be closed.
