### ISSUE TITLE
[BUG] AssertionError: assert <MagicMock name='from_pretrained().decode()' id='140571253705504'> == 'mocked output'

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#281]
/home/v/swarms/tests/models/test_huggingface.py::test_llm_run failed: mock_model = <MagicMock name='from_pretrained' id='140571806989760'>
mock_tokenizer = <MagicMock name='from_pretrained' id='140571829573696'>
llm_instance = <swarms.models.huggingface.HuggingfaceLLM object at 0x7fd96c9ef6a0>

    @patch("swarms.models.huggingface.AutoTokenizer.from_pretrained")
    @patch(
        "swarms.models.huggingface.AutoModelForCausalLM.from_pretrained"
    )
    def test_llm_run(mock_model, mock_tokenizer, llm_instance):
        mock_model.return_value.generate.return_value = "mocked output"
        mock_tokenizer.return_value.encode.return_value = "mocked input"
        result = llm_instance.run("test task")
>       assert result == "mocked output"
E       AssertionError: assert <MagicMock name='from_pretrained().decode()' id='140571253705504'> == 'mocked output'

tests/models/test_huggingface.py:51: AssertionError

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/281">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/281/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/281/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 deleted the tests
