### ISSUE TITLE
[BUG] ImportError: cannot import name 'Gemini' from 'swarms.models' 

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#306]
Traceback (most recent call last):
  File "/home/v/inhouse/gemini.py", line 1, in <module>
    from swarms.models import Gemini
ImportError: cannot import name 'Gemini' from 'swarms.models' (/home/v/.local/lib/python3.10/site-packages/swarms/models/__init__.py)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/306">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/306/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/306/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09  This error has been eliminated
