### ISSUE TITLE
[BUG] ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (/home/v/.local/lib/python3.10/site-packages/huggingface_hub/constants.py)

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#335]
_______________________ ERROR collecting tests/models/test_ssd_1b.py ________________________
ImportError while importing test module '/home/v/vswarms/tests/models/test_ssd_1b.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/models/test_ssd_1b.py:2: in <module>
    from swarms.models.ssd_1b import SSD1B
swarms/models/ssd_1b.py:10: in <module>
    from diffusers import StableDiffusionXLPipeline
../.local/lib/python3.10/site-packages/diffusers/__init__.py:5: in <module>
    from .utils import (
../.local/lib/python3.10/site-packages/diffusers/utils/__init__.py:21: in <module>
    from .constants import (
../.local/lib/python3.10/site-packages/diffusers/utils/constants.py:17: in <module>
    from huggingface_hub.constants import HF_HOME
E   ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (/home/v/.local/lib/python3.10/site-packages/huggingface_hub/constants.py)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/335">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/335/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/335/pledge.svg">
</picture>
</a>

**Comment by ychacha** [comment]
any updates on the this bug?

**Comment by vyomakesh09** [comment]
update your pip
