### ISSUE TITLE
[CLEA] models/anthropic - check_package_version redefined and unused.

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#338]
ruff noticed a re-defined unused method:

```
models/anthropic.py:135:5: F811 Redefinition of unused `check_package_version` from line 32
```
It is both imported from langchain, and defined at line 135.

One or the other should be deleted.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/338">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/338/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/338/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
Similar problem for 
```
models/anthropic.py:174:5: F811 Redefinition of unused `get_pydantic_field_names` from line 34
```
imported from langchain and defined at line 174

**Comment by kyegomez** [comment]
@evelynmitchell just fixed by deleting them
