### ISSUE TITLE
[BUGF] [pydantic.v1] [test_team.py] 

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#342]
```
pydantic-1.10.12 --> 2.5.3

could potentially change the version 

_________________________________ ERROR collecting tests/structs/test_team.py __________________________________
ImportError while importing test module '/home/v/vswarms/tests/structs/test_team.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/structs/test_team.py:6: in <module>
    from swarms.structs.team import Team
../.local/lib/python3.10/site-packages/swarms/structs/team.py:4: in <module>
    from pydantic.v1 import BaseModel, Field, Json, root_validator
E   ModuleNotFoundError: No module named 'pydantic.v1'
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/342">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/342/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/342/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 pull and try again please I removed it
