### ISSUE TITLE
[BUG] TypeError: descriptor 'append' for 'list' objects doesn't apply to a 'Task' object

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#349]
```
[ERROR][ConcurrentWorkflow] descriptor 'append' for 'list' objects doesn't apply to a 'Task' object
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-7-3cd599b21a20>](https://localhost:8080/#) in <cell line: 23>()
     21 
     22 # Add tasks to the workflow
---> 23 workflow.add(task1)
     24 workflow.add(task2)
     25 workflow.add(task3)

1 frames
[/usr/local/lib/python3.10/dist-packages/swarms/structs/recursive_workflow.py](https://localhost:8080/#) in add(self, task, tasks)
     47                     self.tasks.append(task)
     48             else:
---> 49                 self.tasks.append(task)
     50         except Exception as error:
     51             print(f"[ERROR][ConcurrentWorkflow] {error}")

TypeError: descriptor 'append' for 'list' objects doesn't apply to a 'Task' object
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/349">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/349/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/349/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 I have fixed this error by removing `tasks` from the add method
