### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory: 'runs/conversation.json'

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#350]
User: v
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-9-6e7b9c208a3d>](https://localhost:8080/#) in <cell line: 44>()
     42 
     43 # Replace with your LLM instance
---> 44 interactive_conversation(llm)

2 frames
[/usr/local/lib/python3.10/dist-packages/swarms/structs/conversation.py](https://localhost:8080/#) in save_as_json(self, filename)
    230         """
    231         # Save the conversation history as a JSON file
--> 232         with open(filename, "w") as f:
    233             json.dump(self.conversation_history, f)
    234 

FileNotFoundError: [Errno 2] No such file or directory: 'runs/conversation.json'

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/350">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/350/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/350/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 please try again and lmk
