### ISSUE TITLE
[BUG] [concurrent workflow]

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#351]
![Screenshot from 2024-01-11 22-28-29](https://github.com/kyegomez/swarms/assets/54256947/aa4f0496-47cf-4378-bd36-1a710693386c)

**Comment by kyegomez** [comment]
@vyomakesh09 this error will be fixed in the upcoming patch.

**Comment by shersoni610** [comment]
Hi, 
I faced the same issue. Any idea when it will be fixed?

**Comment by evelynmitchell** [comment]
I do not see this issue in my testing. i believe it is fixed.
