### ISSUE TITLE
RecursiveWorkflow example 

### ISSUE THREAD

**Issue by shersoni610** [kyegomez/swarms#353]
Hello,
The RecursiveWorkFlow  example on the  web  produces the following error:

 descriptor 'append' for 'list' objects doesn't apply to a 'Task' object

I was hoping that simple example must work without any issues. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/353">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/353/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/353/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@shersoni610 Please update your swarms package and try again I believe it may be fixed.
