### ISSUE TITLE
psutil problem

### ISSUE THREAD

**Issue by shersoni610** [kyegomez/swarms#354]
Hello,

I created a virtualenv and installed psutil package and it worked fine.
Thereafter, I installed swarms using pip install swarms and using pip install -r requirements.
But doing so, created problem with psutil:Now I get the following error:

ModuleNotFoundError: No module named 'psutil'

What could be the issue?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/354">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/354/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/354/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@shersoni610 please try again when you have a chance I believed I have fixed it!

**Comment by evelynmitchell** [comment]
I see that psutil has been added to the package requirements. I believe this can be closed.
