### ISSUE TITLE
Logging and Monitoring

### ISSUE THREAD

**Issue by shersoni610** [kyegomez/swarms#355]
Hello,

Is there any logging and monitoring functionality available in Swarm?

It seems in the all examples it was not clear if a particular llm, agent, task etc
was successfully created or not.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/355">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/355/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/355/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@shersoni610 I am adding more logging now, thank you for notifying me

**Comment by kyegomez** [comment]
@shersoni610 Let me know if you enjoy the monitoring, each message comes with the [TYPE of Mesage][Class or function][error]
