### ISSUE TITLE
Examples not working: 

### ISSUE THREAD

**Issue by shersoni610** [kyegomez/swarms#356]
Hello,

I  have been trying this software with the examples given. So far,   only a few things works. 

Although  I  get the following mssage from the example below,   it did not the second line.         

swarms is up to date!

from swarms.workers import Worker
from swarms.agents.meta_prompter import MetaPrompterAgent
from swarms.models import OpenAI

# init llm
llm = OpenAI()

# init the meta prompter agent that optimized prompts
meta_optimizer = MetaPrompterAgent(llm=llm)

# init the worker agent
worker = Worker(llm)

# broad task to complete
task = "Create a feedforward in pytorch"

# optimize the prompt
optimized_prompt = meta_optimizer.run(task)

# run the optimized prompt with detailed instructions
result = worker.run(optimized_prompt)

# print
print(result)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/356">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/356/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/356/pledge.svg">
</picture>
</a>

**Comment by vyomakesh09** [comment]
I'm sorry, but this example doesn't exits anymore
