### ISSUE TITLE
[BUG]  [RECURSIVE WORK FLOW EXAMPLE] 

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#360]
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-11-776bf6269c08>](https://localhost:8080/#) in <cell line: 21>()
     19 
     20 # Add tasks to the workflow
---> 21 workflow.add(task1)
     22 workflow.add(task2)
     23 workflow.add(task3)

1 frames
[/usr/local/lib/python3.10/dist-packages/swarms/structs/recursive_workflow.py](https://localhost:8080/#) in add(self, task, tasks)
     56                     )
     57             else:
---> 58                 self.task_pool.append(task)
     59                 logger.info(
     60                     f"[INFO][RecursiveWorkflow] Added task {task} to"

TypeError: descriptor 'append' for 'list' objects doesn't apply to a 'Task' object
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/360">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/360/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/360/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@vyomakesh09 the error has been eliminated
