### ISSUE TITLE
[BUG] [DEP} transformers VipLlavaForConditionalGeneration

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#367]
**Describe the bug**
transformers v4.37.1 is needed for VipLlavaForConditionalGeneration import
see: https://github.com/huggingface/transformers/commit/c7f076a00ee54f777b3d3322c91bc11489a47950

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/367">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/367/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/367/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell just fixed it now

**Comment by evelynmitchell** [comment]
Looking good! Thanks Kye!
