### ISSUE TITLE
[BUG] Error running agent: 'Agent' object has no attribute 'get_llm_init_params'

### ISSUE THREAD

**Issue by arnavsaxena17** [kyegomez/swarms#370]
**Describe the bug**
When running the sample agent for the first time, either in google colab or in the command line, upon calling agent.run("Generate a 10,000 word blog on health and wellness.")

The following response is received :
Initializing Autonomous Agent None...
Autonomous Agent Activated.
All systems operational. Executing task...
ERROR:root:Error running agent: 'Agent' object has no attribute 'get_llm_init_params'
Error running agent: 'Agent' object has no attribute 'get_llm_init_params'

**To Reproduce**
1. Go to 'google colab notebook': https://colab.research.google.com/github/kyegomez/swarms/blob/master/playground/swarms_example.ipynb
2. Add Open AI API Key 
3. Hit Run All
ERROR:root:Error running agent: 'Agent' object has no attribute 'get_llm_init_params'
Error running agent: 'Agent' object has no attribute 'get_llm_init_params'

**Expected behavior**
The bot should be able to return the response as a 10k word blog

<img width="773" alt="Screenshot 2024-01-30 at 15 45 40" src="https://github.com/kyegomez/swarms/assets/16238974/c3da395f-99b6-4616-88a9-c14af5d3bcd1">

<img width="724" alt="Screenshot 2024-01-30 at 15 42 25" src="https://github.com/kyegomez/swarms/assets/16238974/f168b8ae-d6dc-49f7-8c3a-ecb108df1f16">

**Screenshots**

**Additional context**

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/370">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/370/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/370/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@arnavsaxena17 Hey I have fixed it, please give it a try again.

**Comment by arnavsaxena17** [comment]
Umm, tried it. Still the same error

**Comment by kyegomez** [comment]
@arnavsaxena17 try deleting the swarms package with: 

```
pip uninstall swarms
```

Then try:

```
pip cache purge
```

Then

```
pip3 install -U swarms
```

If this does not work, join the Agora discord voice channel and show me your screen and I'll help you:

https://discord.gg/kQa9dFyB7t

**Comment by arnavsaxena17** [comment]
Pinging you on discord

**Comment by kyegomez** [comment]
@arnavsaxena17 please excuse me for the inconvenience.

try:

`pip3 install swarms==3.9.2`

**Comment by arnavsaxena17** [comment]
Yes, works in linux but not in macos. Some problem with sonoma 14

**Comment by kyegomez** [comment]
@arnavsaxena17 What's the full error?

**Comment by arnavsaxena17** [comment]
In my macos, 
When I call

>>> from swarms import OpenAIChat, Agent

I get the error :
>>> 'NoneType' object has no attribute 'cadam32bit_grad_fp32'


And then subsequently, agent.run("Generate a 10,000 word blog on health and wellness.") returns None.
Screenshot below :

<img width="541" alt="Screenshot 2024-02-05 at 00 34 23" src="https://github.com/kyegomez/swarms/assets/16238974/eefd7ca5-40a2-469d-a501-7ff7d917930e">
