### ISSUE TITLE
[BUG] UnboundLocalError: cannot access local variable 'added_to_db' where it is not associated with a value Implicitly cleaning up <TemporaryDirectory '/var/folders/lz/8cyyy_pj1xqf05jck98kpkrc0000gn/T/tmpzdbwcgp_'>

### ISSUE THREAD

**Issue by starshipvc** [kyegomez/swarms#401]
``` 
athena@Athenas-MacBook-Pro athena % python3.11 sam_altman.py
swarms is up to date!
Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
Importing PromptTemplate from langchain root module is no longer supported. Please use langchain.prompts.PromptTemplate instead.
distutils Version classes are deprecated. Use packaging.version instead.
distutils Version classes are deprecated. Use packaging.version instead.
ChromaDB collection created: swarms with metric: cosine and output directory: swarms                                                              
Traversing directory: artifacts/sam_altman                                                                                                        
Traceback (most recent call last):
    chromadb = ChromaDB(
               ^^^^^^^^^
line 117, in __init__
    self.traverse_directory()
line 207, in traverse_directory
    return added_to_db
           ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'added_to_db' where it is not associated with a value
Implicitly cleaning up <TemporaryDirectory '/var/folders/lz/8cyyy_pj1xqf05jck98kpkrc0000gn/T/tmpzdbwcgp_'>
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/401">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/401/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/401/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
Hi starshipvc,

The error:
```
UnboundLocalError: cannot access local variable 'added_to_db' where it is not associated with a value
```
will occur when the directory of files you are trying to add to chromadb doesn't have any files to add.

Could you check that the directory you are adding has files, and if so, how many are of the correct type to add?

In addition, if you could share the code you are running, that would be very helpful for debugging.

I hope this helps. Please ask any questions you may have.
Evelyn Mitchell

**Comment by kyegomez** [comment]
@starshipvc fixed with swarms_memory
