### ISSUE TITLE
[BUG] TypeError: SegmentAPI.get_or_create_collection() got an unexpected keyword argument 'data_loader' Implicitly cleaning up <TemporaryDirectory '/var/folders/lz/8cyyy_pj1xqf05jck98kpkrc0000gn/T/tmpc96i__sk'>

### ISSUE THREAD

**Issue by starshipvc** [kyegomez/swarms#402]
```
swarms is up to date!
Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
Importing PromptTemplate from langchain root module is no longer supported. Please use langchain.prompts.PromptTemplate instead.
distutils Version classes are deprecated. Use packaging.version instead.
distutils Version classes are deprecated. Use packaging.version instead.
Traceback (most recent call last):
    chromadb = ChromaDB(
               ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/swarms/memory/chroma_db.py", line 98, in __init__
    self.collection = chroma_client.get_or_create_collection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SegmentAPI.get_or_create_collection() got an unexpected keyword argument 'data_loader'
Implicitly cleaning up <TemporaryDirectory '/var/folders/lz/8cyyy_pj1xqf05jck98kpkrc0000gn/T/tmpc96i__sk'>
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/402">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/402/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/402/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
Hi starshipvc,
Would you be able to share the program you are running that calls swarms? /Users/athena/Desktop/athena/sam_altman.py
That would help.

The error ```TypeError: SegmentAPI.get_or_create_collection() got an unexpected keyword argument 'data_loader'``` is in that code, which is calling a chromaDB function, get_or_create_collection which uses the keyword argument data_loader.

data_loader can take only two values:
None
or 
a function which doesn't take any arguments and returns a value.

I don't know which way data_loader is being called, which is triggering the type error.

Thank you and please ask any questions you may have.
Evelyn Mitchell
