### ISSUE TITLE
[BUG] [   Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)] 

### ISSUE THREAD

**Issue by starshipvc** [kyegomez/swarms#403]
```
swarms is up to date!
Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
Importing PromptTemplate from langchain root module is no longer supported. Please use langchain.prompts.PromptTemplate instead.
distutils Version classes are deprecated. Use packaging.version instead.
distutils Version classes are deprecated. Use packaging.version instead.
Traceback (most recent call last):
    llm = OpenAIChat(
          ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for OpenAIChat
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
Implicitly cleaning up <TemporaryDirectory '/var/folders/lz/8cyyy_pj1xqf05jck98kpkrc0000gn/T/tmp31ymezl9'>
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/403">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/403/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/403/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
Hi starshipvc,

In order to run swarms using OpenAI API, you need to set the key as an environment variable called OPENAI_API_KEY or as a name parameter;
```
openai_api_key = "put your key here"
```

Please let me know if this helped, and ask any questions you may have.

Evelyn Mitchell

**Comment by vyomakesh09** [comment]
please do this 

$export OPENAI_API_KEY='your_api_key'
