### ISSUE TITLE
[BUG] Unable to run `SequentialWorkflow`

### ISSUE THREAD

**Issue by adtygan** [kyegomez/swarms#452]
**Describe the bug**
I'm trying to run a modified version (explained the change in **To Reproduce** section) of "Example 1: Adding Tasks to a Sequential Workflow" from the docs [here](https://swarms.apac.ai/en/latest/swarms/structs/sequential_workflow/) and run into the following error:
<img width="826" alt="Screenshot 2024-04-25 at 3 38 35 PM" src="https://github.com/kyegomez/swarms/assets/51450254/6fe9465f-f21d-4da3-babf-769b29632e20">

Moreover, the 2 agents don't seem to be solving the task given to them. 
<img width="1129" alt="Screenshot 2024-04-25 at 3 39 54 PM" src="https://github.com/kyegomez/swarms/assets/51450254/5f47c6da-9f35-4a39-87e9-baaecbf6b260">

**To Reproduce**
The code given in the blog post raises an error in the section `#Create the Sequential Workflow` as it expects the agents to be specified. Hence I passed them as parameters using `agents=[flow1,flow2]`. Code snippet to reproduce the behavior:

```
from swarms.models import OpenAIChat
from swarms.structs import Agent
from swarms.structs.sequential_workflow import SequentialWorkflow

# Initialize the language model agent (e.g., GPT-3)
llm = OpenAIChat(
    openai_api_key="", # Enter OpenAI API key here
    temperature=0.5,
    max_tokens=3000,
)

# Initialize flows for individual tasks
flow1 = Agent(llm=llm, max_loops=1, dashboard=False)
flow2 = Agent(llm=llm, max_loops=1, dashboard=False)

# Create the Sequential Workflow
workflow = SequentialWorkflow(max_loops=1, agents=[flow1,flow2])

# Add tasks to the workflow
workflow.add("Generate a 10,000 word blog on health and wellness.", flow1)
workflow.add("Summarize the generated blog", flow2)

# Run the workflow
workflow.run()

# Output the results
for task in workflow.tasks:
    print(f"Task: {task.description}, Result: {task.result}")
```

**Expected behavior**
At this stage, the agents are initialized and the `run()` function must iterate through each agent, calling each agent to execute tasks.

**Additional context**
The part of the code responsible for failure is: https://github.com/kyegomez/swarms/blob/fe5a3180c19c0d5f2e3d729f0987be0df6b1651c/swarms/structs/sequential_workflow.py#L150 `

`workflow_bootup()` is defined in https://github.com/kyegomez/swarms/blob/fe5a3180c19c0d5f2e3d729f0987be0df6b1651c/swarms/structs/base_workflow.py#L371

So in my understanding, `swarms/structs/sequential_workflow.py` is not properly importing from `swarms/structs/base_workflow.py`.

Request some assistance on this. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/452">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/452/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/452/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@adtygan Fixing it right now, it'll be finished soon. excuse me

**Comment by kyegomez** [comment]
@adtygan fixed this using `AgentRearrange` located here: https://swarms.apac.ai/en/latest/swarms/structs/agent_rearrange/
