### ISSUE TITLE
[BUG] ImportError: cannot import name 'ChromaDB'

### ISSUE THREAD

**Issue by behroozazarkhalili** [kyegomez/swarms#477]
**Describe the bug**
```python
ImportError: cannot import name 'ChromaDB' from 'swarms' (/home/ermia/anaconda3/envs/deep-shap/lib/python3.10/site-packages/swarms/__init__.py)
```

**To Reproduce**
Here's the code I'm running:

```python
from swarms import Agent, ChromaDB, OpenAIChat

# Making an instance of the ChromaDB class
memory = ChromaDB(
    metric="cosine",
    n_results=3,
    output_dir="results",
    docs_folder="docs",
)

# Initializing the agent with the Gemini instance and other parameters
agent = Agent(
    agent_name="Covid-19-Chat",
    agent_description=(
        "This agent provides information about COVID-19 symptoms."
    ),
    llm=OpenAIChat(),
    max_loops="auto",
    autosave=True,
    verbose=True,
    long_term_memory=memory,
    stopping_condition="finish",
)

# Defining the task and image path
task = ("What are the symptoms of COVID-19?",)

# Running the agent with the specified task and image
out = agent.run(task)
print(out)
```

**Expected behavior**
It should run without any errors as it is an example in the readme.md of the repository.

**Screenshots**
![image](https://github.com/kyegomez/swarms/assets/80390531/ffd6114c-e39d-4367-a5c6-c504bb716fc5)

**Additional context**

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/477">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/477/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/477/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@behroozazarkhalili this code was taken out of the main swarms package to reduce redundancy, you can import it from here:

https://github.com/kyegomez/swarms/blob/master/playground/memory/chroma_db.py

**Comment by behroozazarkhalili** [comment]
> @behroozazarkhalili this code was taken out of the main swarms package to reduce redundancy, you can import it from here:
> 
> https://github.com/kyegomez/swarms/blob/master/playground/memory/chroma_db.py
It is not the correct way to remove the bug. I think we should update the readme file to effectively handle this bug.

**Comment by kyegomez** [comment]
@behroozazarkhalili the code example has been removed! Let me know if you have any other questions!

**Comment by kyegomez** [comment]
@behroozazarkhalili try 

```
from swarms_memory import ChromaDB
```

**Comment by kyegomez** [comment]
@behroozazarkhalili @www lmk will be closing soon
