### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Caerii** [kyegomez/swarms#49]
**Describe the bug**
We cannot create a new worker node using example.py. From a fresh download of Swarms using Python 3.11 on Windows 11, trying to launch example.py through windows command terminal leads to an error. 

**To Reproduce**
1.  Download swarms
2.  Install requirements.txt
3.  setx OPENAI_API_KEY "xxx"
4. py example.py

**Expected behavior**
The example is not running and creating nodes that are doing work.

**Screenshots**
![image](https://github.com/kyegomez/swarms/assets/67016155/f92134ea-d438-44e8-8150-1501e8a8c18e)

**Additional context**
Perhaps the code is not compatible with more recent versions of Python? But I think the issue is more likely that some specific type errors might be occurring with the Tool object?

I gave the error and the code to ChatGPT and this is what it says:

The error message you provided indicates that there's an issue with the func parameter when initializing a Tool object, which is part of a larger codebase related to a project involving hierarchical swarms. Let's break down the error message and the relevant parts of your code to understand what's going on:

plaintext
Copy code
<swarms.workers.worker_node.WorkerNode object at 0x000001E2AA5BF350> is not callable (type=type_error.callable; value=<swarms.workers.worker_node.WorkerNode object at 0x000001E2AA5BF350>)
This error message indicates that an object of type swarms.workers.worker_node.WorkerNode located at memory address 0x000001E2AA5BF350 is not callable. In Python, a "callable" refers to something that can be called like a function. In this case, the code is trying to treat this object as if it were a function, but it's not designed to be called in this manner.

Looking at your code, the relevant portion seems to be in the HierarchicalSwarm class initialization, specifically in the lines where the Tool objects are being created for both self.worker_node and self.boss_node.

Here's the relevant part of your code:

python
Copy code
self.worker_node = WorkerNode(
    openai_api_key=self.openai_api_key,
    temperature=self.temperature,
    human_in_the_loop=self.human_in_the_loop,
    verbose=self.verbose
)

self.boss_node = BossNode(
    api_key=self.openai_api_key,
    worker_node=self.worker_node,
    llm_class=OpenAI,
    max_iterations=self.max_iterations,
    verbose=self.verbose
)
The WorkerNode and BossNode classes are likely designed to handle different aspects of the swarm, and they are not intended to be directly callable as functions. However, the Tool objects within their initialization seem to expect a callable function as the func parameter.

To resolve this issue, you'll need to review the documentation or implementation of the Tool class to understand how it should be used and what the func parameter expects. If it's indeed expecting a callable function, you might need to refactor your code to provide appropriate functions for these Tool objects instead of passing instances of WorkerNode and BossNode.

If these objects are not meant to be used as functions, you might need to adjust how you're initializing the Tool objects or how you're using the Tool class within your codebase.

**Comment by kyegomez** [comment]
@Caerii Hey please excuse me for this, I have fixed this now. Let me know if you want any more help!
