### ISSUE TITLE
[BUG] ToolAgent example

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#510]
This is likely fixable by modifying the swarms __init__.py

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-9-715acb48d350>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 from swarms import ToolAgent
----> 5 from swarms.utils.json_utils import base_model_to_json
      6 
      7 # Load the pre-trained model and tokenizer

ModuleNotFoundError: No module named 'swarms.utils.json_utils'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/510">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/510/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/510/pledge.svg">
</picture>
</a>

**Comment by Occupying-Mars** [comment]
the example in the readme is wrong for where you are trying to use it. this [pr](https://github.com/kyegomez/swarms/pull/655) should fix it and the actual import is  `from swarms.tools.json_utils import base_model_to_json`

**Comment by evelynmitchell** [comment]
The merged PR 655 fixed this. Closing
