### ISSUE TITLE
[BUG] SwarmNetwork

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#513]
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-14-1f396324b767>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 # Import the OpenAIChat model and the Agent struct
----> 6 from swarms import Agent, OpenAIChat, SwarmNetwork
      7 
      8 # Load the environment variables

ImportError: cannot import name 'SwarmNetwork' from 'swarms' (/usr/local/lib/python3.10/dist-packages/swarms/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/513">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/513/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/513/pledge.svg">
</picture>
</a>

**Comment by sambhavnoobcoder** [comment]
To solve this bug, we need to update the import statement. The SwarmNetwork class should be imported from `swarms.structs` instead of directly from `swarms` . Here's how to fix the import:
```
from swarms import Agent
from swarm_models import OpenAIChat
from swarms.structs import SwarmNetwork
```
This change addresses the ImportError by correctly importing SwarmNetwork from the `swarms.structs` module.
You can reference this change in the following line : 
```
from swarms.structs.swarm_net import SwarmNetwork
```
located at the top imports of the structs/__init__.py

**Comment by kyegomez** [comment]
@evelynmitchell @sambhavnoobcoder yeah, the swarm network has been dropped out of production because it's not production grade yet. I will close this error for now.
