### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by geeknik** [kyegomez/swarms#52]
**Describe the bug**
`ImportError: cannot import name 'swarm' from 'swarms'`

**To Reproduce**
1. pip3 install swarms
2. run example.py:
```
from swarms import swarm

objective = "What is the capital of the Uk"

swarm(objective)
```
3. See the error
```
Traceback (most recent call last):
  File "/home/geeknik/example.py", line 1, in <module>
    from swarms import swarm
ImportError: cannot import name 'swarm' from 'swarms' (/home/geeknik/.local/lib/python3.11/site-packages/swarms/__init__.py)
```

**Expected behavior**
swarms should run as we just copied and pasted from the example in the README.

**Comment by kyegomez** [comment]
@geeknik Hey please excuse me, the swarms class is being renovated for now, we're building up all the layers of abstraction to the swarm level now. The worker is available!

-> model
-> agent
-> worker
-> swarm
-> hive(swarm of swarms)
