### ISSUE TITLE
`artifacts_main` directory missing?

### ISSUE THREAD

**Issue by aimzieslol** [kyegomez/swarms#521]
### Context ###

`git clone`d the project into Google Colab. Used `pip install -e .` to make sure the requirements were in the environment. Added `swarms` to the `sys.path.`

### Problem ###

There doesn't seem to be an `artifact_main.py` in the `artifacts` directory which causes the imports to fail here:

https://github.com/kyegomez/swarms/blob/9366437976a1be45d7f60c7d4af22e41a3c67276/swarms/artifacts/__init__.py#L3

### Telemetry ###

As a side note, please **document** the ability to opt out of the embedded telemetry initialized here:

```
def activate_sentry():
    if use_telementry == "True":
        sentry_sdk.init(
            dsn="https://5d72dd59551c02f78391d2ea5872ddd4@o4504578305490944.ingest.us.sentry.io/4506951704444928",
            traces_sample_rate=1.0,
            profiles_sample_rate=1.0,
            enable_tracing=True,
            debug=True,
        )
```

I know it means a lot to some people the fact they can use `os.environ['USE_TELEMETRY'] = False` to opt out. I, personally, don't care; you've done great work and are offering this for free so more power to ya.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/521">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/521/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/521/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment]
I believe the Artifacts import problem has been fixed. Can you update and try again?

**Comment by evelynmitchell** [comment]
I'll submit a doc patch for the telemetry issue. The brief answer is to set the environment variable:
```
USE_TELEMETRY="False"
```
to turn off telemetry and 
```
USE_TELEMETRY="True"
```
to turn it on.
