### ISSUE TITLE
[BUG] 404 for linked explorer url: https://swarms.world/platform/explorer

### ISSUE THREAD

**Issue by joshcarp** [kyegomez/swarms#533]
**Describe the bug**
Dead link to https://swarms.world/platform/explorer where the swarms platform explorer is hosted at https://swarms.world

**To Reproduce**

1. After sign up here, the "Explorer button" links to https://swarms.world/platform/explorer which returns 404

**Expected behavior**
HTTP redirect should be redirecting https://swarms.world/platform/explorer to https://swarms.world 

**Screenshots**

![9b09647a7fd9fa658f3a530309af5f2a](https://github.com/user-attachments/assets/fb4f7b2b-c99d-4e54-9733-20a27497d967)
<img width="344" alt="image" src="https://github.com/user-attachments/assets/57d761f4-b665-4c05-b736-ac861df04f30">

**Additional context**

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/533">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/533/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/533/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@joshcarp appreciate that, yeah we just deleted the whole landing page
