### ISSUE TITLE
cant install 

### ISSUE THREAD

**Issue by jmanhype** [kyegomez/swarms#6]
Failed to build Pillow sentencepiece scikit-image
ERROR: Could not build wheels for Pillow, sentencepiece, scikit-image, which is required to install pyproject.toml-based projects
PS C:\Users\strau>

**Comment by kyegomez** [comment]
Hey can you try upgrading pip install --upgrade swarms and or git clone method

**Comment by kyegomez** [comment]
@jmanhype try installing again please it should work now
