### ISSUE TITLE
[BUG] Unable to import AzureOpenAI

### ISSUE THREAD

**Issue by techthiyanes** [kyegomez/swarms#602]
**Describe the bug**
Unable to import AzureOpenAI

**To Reproduce**
Import AzureOpenAI from swarms

**Expected behavior**
Should be able to import AzureOpenAI

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/602">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/602/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/602/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@techthiyanes try the swarm_models package. all of the models have been moved here

```
$ pip3 install -U swarm_models
```

[Documentation is here](https://docs.swarms.world/en/latest/swarms/models/models_available_overview/)

```
import os
from dotenv import load_dotenv
from swarms import AzureOpenAI

# Load the environment variables
load_dotenv()

# Create an instance of the AzureOpenAI class
model = AzureOpenAI(
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    deployment_name=os.getenv("AZURE_OPENAI_DEPLOYMENT"),
    openai_api_version=os.getenv("OPENAI_API_VERSION"),
    openai_api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    azure_ad_token=os.getenv("AZURE_OPENAI_AD_TOKEN"),
)

# Define the prompt
prompt = (
    "Analyze this load document and assess it for any risks and"
    " create a table in markdown format."
)

# Generate a response
response = model(prompt)
print(response)
```

**Comment by techthiyanes** [comment]
Thank you so much on your response. I am able to import it now.
