### ISSUE TITLE
Error installing swarms 5.8.7

### ISSUE THREAD

**Issue by jcooper212** [kyegomez/swarms#614]
Am installing swarms for the first time...need help...

venv) (venv) jcooper@iMac swarms % python --version
Python 3.13.0

(venv) (venv) jcooper@iMac swarms % pip install swarms==5.8.7
Collecting swarms==5.8.7
  Using cached swarms-5.8.7-py3-none-any.whl.metadata (93 kB)
Collecting Pillow==10.4.0 (from swarms==5.8.7)
  Using cached pillow-10.4.0-cp313-cp313-macosx_10_13_x86_64.whl.metadata (9.2 kB)
Collecting PyYAML (from swarms==5.8.7)
  Using cached PyYAML-6.0.2-cp313-cp313-macosx_10_13_x86_64.whl.metadata (2.1 kB)
Collecting aiofiles (from swarms==5.8.7)
  Using cached aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Collecting asyncio<4.0,>=3.4.3 (from swarms==5.8.7)
  Using cached asyncio-3.4.3-py3-none-any.whl.metadata (1.7 kB)
Collecting backoff==2.2.1 (from swarms==5.8.7)
  Using cached backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Collecting black (from swarms==5.8.7)
  Using cached black-24.10.0-cp313-cp313-macosx_10_13_x86_64.whl.metadata (79 kB)
Collecting clusterops (from swarms==5.8.7)
  Using cached clusterops-0.0.5-py3-none-any.whl.metadata (11 kB)
Collecting docstring_parser==0.16 (from swarms==5.8.7)
  Using cached docstring_parser-0.16-py3-none-any.whl.metadata (3.0 kB)
Collecting fastapi (from swarms==5.8.7)
  Using cached fastapi-0.115.3-py3-none-any.whl.metadata (27 kB)
Collecting langchain-community==0.0.29 (from swarms==5.8.7)
  Using cached langchain_community-0.0.29-py3-none-any.whl.metadata (8.3 kB)
Collecting langchain-experimental==0.0.55 (from swarms==5.8.7)
  Using cached langchain_experimental-0.0.55-py3-none-any.whl.metadata (2.1 kB)
Collecting loguru==0.7.2 (from swarms==5.8.7)
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting networkx (from swarms==5.8.7)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting openai<2.0,>=1.30.1 (from swarms==5.8.7)
  Using cached openai-1.52.2-py3-none-any.whl.metadata (24 kB)
Collecting psutil (from swarms==5.8.7)
  Using cached psutil-6.1.0-cp36-abi3-macosx_10_9_x86_64.whl.metadata (22 kB)
Collecting pydantic==2.8.2 (from swarms==5.8.7)
  Using cached pydantic-2.8.2-py3-none-any.whl.metadata (125 kB)
Collecting pypdf==4.3.1 (from swarms==5.8.7)
  Using cached pypdf-4.3.1-py3-none-any.whl.metadata (7.4 kB)
Collecting python-dotenv (from swarms==5.8.7)
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting sentry-sdk[http] (from swarms==5.8.7)
  Using cached sentry_sdk-2.17.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting swarm-models (from swarms==5.8.7)
  Using cached swarm_models-0.1.1-py3-none-any.whl.metadata (9.2 kB)
Collecting swarms-cloud<5,>=0.4.4 (from swarms==5.8.7)
  Using cached swarms_cloud-0.4.4-py3-none-any.whl.metadata (8.3 kB)
Collecting swarms-memory (from swarms==5.8.7)
  Using cached swarms_memory-0.1.2-py3-none-any.whl.metadata (12 kB)
Collecting tenacity==8.5.0 (from swarms==5.8.7)
  Using cached tenacity-8.5.0-py3-none-any.whl.metadata (1.2 kB)
Collecting termcolor (from swarms==5.8.7)
  Using cached termcolor-2.5.0-py3-none-any.whl.metadata (6.1 kB)
Collecting tiktoken (from swarms==5.8.7)
  Using cached tiktoken-0.8.0-cp313-cp313-macosx_10_13_x86_64.whl.metadata (6.6 kB)
Collecting toml (from swarms==5.8.7)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
INFO: pip is looking at multiple versions of swarms to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement torch<3.0,>=2.1.1 (from swarms) (from versions: none)
ERROR: No matching distribution found for torch<3.0,>=2.1.1
(venv) (venv) jcooper@iMac swarms % python -m pip install swarms==5.8.7 
Collecting swarms==5.8.7
  Using cached swarms-5.8.7-py3-none-any.whl.metadata (93 kB)
Collecting Pillow==10.4.0 (from swarms==5.8.7)
  Using cached pillow-10.4.0-cp313-cp313-macosx_10_13_x86_64.whl.metadata (9.2 kB)
Collecting PyYAML (from swarms==5.8.7)
  Using cached PyYAML-6.0.2-cp313-cp313-macosx_10_13_x86_64.whl.metadata (2.1 kB)
Collecting aiofiles (from swarms==5.8.7)
  Using cached aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Collecting asyncio<4.0,>=3.4.3 (from swarms==5.8.7)
  Using cached asyncio-3.4.3-py3-none-any.whl.metadata (1.7 kB)
Collecting backoff==2.2.1 (from swarms==5.8.7)
  Using cached backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Collecting black (from swarms==5.8.7)
  Using cached black-24.10.0-cp313-cp313-macosx_10_13_x86_64.whl.metadata (79 kB)
Collecting clusterops (from swarms==5.8.7)
  Using cached clusterops-0.0.5-py3-none-any.whl.metadata (11 kB)
Collecting docstring_parser==0.16 (from swarms==5.8.7)
  Using cached docstring_parser-0.16-py3-none-any.whl.metadata (3.0 kB)
Collecting fastapi (from swarms==5.8.7)
  Using cached fastapi-0.115.3-py3-none-any.whl.metadata (27 kB)
Collecting langchain-community==0.0.29 (from swarms==5.8.7)
  Using cached langchain_community-0.0.29-py3-none-any.whl.metadata (8.3 kB)
Collecting langchain-experimental==0.0.55 (from swarms==5.8.7)
  Using cached langchain_experimental-0.0.55-py3-none-any.whl.metadata (2.1 kB)
Collecting loguru==0.7.2 (from swarms==5.8.7)
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting networkx (from swarms==5.8.7)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting openai<2.0,>=1.30.1 (from swarms==5.8.7)
  Using cached openai-1.52.2-py3-none-any.whl.metadata (24 kB)
Collecting psutil (from swarms==5.8.7)
  Using cached psutil-6.1.0-cp36-abi3-macosx_10_9_x86_64.whl.metadata (22 kB)
Collecting pydantic==2.8.2 (from swarms==5.8.7)
  Using cached pydantic-2.8.2-py3-none-any.whl.metadata (125 kB)
Collecting pypdf==4.3.1 (from swarms==5.8.7)
  Using cached pypdf-4.3.1-py3-none-any.whl.metadata (7.4 kB)
Collecting python-dotenv (from swarms==5.8.7)
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting sentry-sdk[http] (from swarms==5.8.7)
  Using cached sentry_sdk-2.17.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting swarm-models (from swarms==5.8.7)
  Using cached swarm_models-0.1.1-py3-none-any.whl.metadata (9.2 kB)
Collecting swarms-cloud<5,>=0.4.4 (from swarms==5.8.7)
  Using cached swarms_cloud-0.4.4-py3-none-any.whl.metadata (8.3 kB)
Collecting swarms-memory (from swarms==5.8.7)
  Using cached swarms_memory-0.1.2-py3-none-any.whl.metadata (12 kB)
Collecting tenacity==8.5.0 (from swarms==5.8.7)
  Using cached tenacity-8.5.0-py3-none-any.whl.metadata (1.2 kB)
Collecting termcolor (from swarms==5.8.7)
  Using cached termcolor-2.5.0-py3-none-any.whl.metadata (6.1 kB)
Collecting tiktoken (from swarms==5.8.7)
  Using cached tiktoken-0.8.0-cp313-cp313-macosx_10_13_x86_64.whl.metadata (6.6 kB)
Collecting toml (from swarms==5.8.7)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
INFO: pip is looking at multiple versions of swarms to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement torch<3.0,>=2.1.1 (from swarms) (from versions: none)
ERROR: No matching distribution found for torch<3.0,>=2.1.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/614">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/614/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/614/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@jcooper212 the download should be okay, try running a simple agent script in the readme. I don't think there was an error here.

**Comment by kyegomez** [comment]
@jcooper212 you are good to go. try running a file in the examples and let me know what happens
