### ISSUE TITLE
[BUG] Canot start swarms because of undefined ENV var WORKSPACE_DIR

### ISSUE THREAD

**Issue by Fadope1** [kyegomez/swarms#618]
**Describe the bug**
Happened directly after installing. Can't interact with the cli nor can I start a script. I always get the same error.
It seems that the variable WORKSPACE_DIR needs to be set for some reason.

**To Reproduce**
1. Install swarms
2. Run anything with swarms

**Expected behavior**
It should run.

**Traceback*
.venv/lib/python3.11/site-packages/swarms/utils/loguru_logger.py", line 10, in <module>
    os.path.join(WORKSPACE_DIR, "swarms.log"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/618">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/618/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/618/pledge.svg">
</picture>
</a>

**Comment by Fadope1** [comment]
Found that in the docs it says to add this ENV var. But in the github README its not there.

**Comment by kyegomez** [comment]
@Fadope1 Hey excuse the error, we showcase the setting in the requirements section of the README.md let me know if you would like more assistance!
