### ISSUE TITLE
[BUG] "No module name 'uvloop'

### ISSUE THREAD

**Issue by ec-lp** [kyegomez/swarms#623]
**Describe the bug**

**To Reproduce**
1. windows 11, conda env python 3.12
2. pip install swarms
3. (some difficulty with installation requiring compilation of chroma-hnswlib, which can be resolved by installing MS build tools or with manually installing conda package)
4. code crashes at `>from swarms import Agent`

**Expected behavior**
example code would run seemlessly

**Screenshots**

**Additional context**
uvloop not in requirements or pyproject.toml

uvloop not compatible with windows.

problematic uvloop import in file `...swarms\structs\multi_agent_exec.py`

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/623">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/623/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/623/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@ec-lp update your swarms pip package `pip3 install -U swarms`! and let me know of the new changes
