### ISSUE TITLE
[FEAT][`GroupChat` class where it intakes multiple `Flow` agents as inputs and the enables all to all communication

### ISSUE THREAD

**Issue by ZackBradshaw** [kyegomez/swarms#83]
1. Understand the Current Implementation: Before you start, make sure you understand how the Flow class currently works. It's designed to handle sequential responses from a language model, with features like user-defined queries, dynamic generation until a <DONE> token is outputted, and interactive modes where the AI generates a response and then waits for user input.

2. Define the Group Chat Feature: Next, you need to define what the group chat feature should do. For example, it might need to handle multiple users, keep track of the order of messages, and allow users to join or leave the chat.

3. Design the Interface: Think about how the group chat feature will be used. You might need to add new methods to the Flow class, or modify existing ones. For example, you might need a method to add a user to the chat, and another method to handle a message from a user.

4. Implement the Feature: Once you've designed the interface, you can start implementing the feature. You might need to modify the Flow class and other parts of the swarms framework. Make sure to test your changes as you go along to ensure everything still works as expected.

5. Look at AutoGen for Inspiration: Microsoft's AutoGen is a tool for automatically generating Python code, and it might give you some ideas for how to implement the group chat feature. However, keep in mind that AutoGen is a code generation tool, while swarms is a framework for controlling language models, so not everything in AutoGen will be directly applicable.

6. Document Your Changes: Finally, make sure to document your changes. This includes both code comments and user-facing documentation. You should explain how to use the group chat feature, and any limitations it might have.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/83">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/83/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/83/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@ZackBradshaw this has been completed so far, now we need to add useful methods for control and reliability
