### ISSUE TITLE
[BUG] Command 'Dev Containers: Rebuild and Reopen in Container resulted in an error

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#90]
Command 'Dev Containers: Rebuild and Reopen in Container resulted in an error
Command failed: /usr/share/code/code -ms-enable-electron-run-as node /home/v/vscode/extensions/ms-vscode remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js read-configuration -workspace-folder /home/v/swarms -log-level debug-log-format json -config /home/v/swarms/.devcontainer/ devcontainer json -include merged-configuration -mount-workspace-gitroot 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/90">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/90/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/90/pledge.svg">
</picture>
</a>

**Comment by ZackBradshaw** [comment]
run the second option for now 
![Screenshot 2023-11-03 160638](https://github.com/kyegomez/swarms/assets/21285642/3931f4ff-a70a-40d1-aad1-038018c3d764)
But venv will work too for now if your able to get that working for you
