### ISSUE TITLE
[BUG] module not found langchain schema vectorstore

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#99]
**Describe the bug**
ModuleNotFoundError: No module named 'langchain.schema.vectorstore'

**To Reproduce**

pip install swarms

import swarms

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/99">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/99/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/99/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell this issue has been handled! Removed all calls to worker which called these tools!
